"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var aonColors;
(function (aonColors) {
    aonColors["blue"] = "#012774";
    aonColors["blueLighter"] = "#0138A7";
    aonColors["blueDarker"] = "#011E5B";
    aonColors["midnight"] = "#001135";
    aonColors["teal"] = "#007FAA";
    aonColors["tealLighter"] = "#00A5DD";
    aonColors["tealDarker"] = "#005977";
    aonColors["aqua"] = "#4CBAEB";
    aonColors["grayA"] = "#2E2E2E";
    aonColors["grayALighter"] = "#545454";
    aonColors["grayADarker"] = "#141414";
    aonColors["grayB"] = "#4C4D4F";
    aonColors["grayC"] = "#696969";
    aonColors["grayCLighter"] = "#8F8F8F";
    aonColors["grayCDarker"] = "#5C5C5C";
    aonColors["grayD"] = "#9B9B9B";
    aonColors["grayE"] = "#C0C0C0";
    aonColors["grayF"] = "#E4E4E4";
    aonColors["grayG"] = "#F8F8F8";
    aonColors["errorRed"] = "#BF4C4A";
    aonColors["warningYellow"] = "#F0A800";
    aonColors["successGreen"] = "#7AB800";
    aonColors["brandRed"] = "#E11B22";
    aonColors["black"] = "#000000";
    aonColors["white"] = "#FFFFFF";
})(aonColors = exports.aonColors || (exports.aonColors = {}));
